### ISSUE TITLE
More about Android

### ISSUE THREAD

**Issue by a-thomas** [blemale/tech-watch-4-excilys-interns#2]
#### Developers:
- Roman Nurik (Googler) http://roman.nurik.net/
- Mark Murphy - @commonsguy : 
  his blog: http://commonsware.com/blog/
  his amazing book: http://commonsware.com/ 
  his twitter: @commonsguy 
#### Newsletters / Google groups / Communities G+:

Android weekly http://androidweekly.net/
Android developers google groups : https://groups.google.com/forum/?fromgroups#!forum/android-developers
Android community on G+ : https://plus.google.com/u/0/communities/105153134372062985968
#### About UI:

AndroidUiPatterns http://www.androiduipatterns.com/

**Comment by jeremiemartinez** [comment]
+1 with http://www.androidviews.net/
